trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'
  platform: 'Any CPU'
  outputDir: '$(Build.ArtifactStagingDirectory)/output'

steps:
  # 1. Instalacja .NET SDK (wersja MAUI, np. 7.0)
  - task: UseDotNet@2
    inputs:
      packageType: 'sdk'
      version: '7.x.x'  # Użyj odpowiedniej wersji SDK dla MAUI
      installationPath: $(Agent.ToolsDirectory)/dotnet

  # 2. Przywrócenie pakietów NuGet
  - task: NuGetToolInstaller@1
  - task: NuGetCommand@2
    inputs:
      restoreSolution: '**/*.sln'

  # 3. Kompilacja projektu
  - task: DotNetCoreCLI@2
    inputs:
      command: 'build'
      projects: '**/*.csproj'
      arguments: '--configuration $(buildConfiguration) -p:Platform=$(platform)'

  # 4. Kompilacja dla Windows
  - task: DotNetCoreCLI@2
    inputs:
      command: 'publish'
      projects: '**/*.csproj'
      arguments: '-f:net7.0-windows -c:$(buildConfiguration) -o:$(outputDir)'

  # 5. Przechowywanie wyników kompilacji jako artefaktów
  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(outputDir)'
      ArtifactName: 'drop'
      publishLocation: 'Container'

